server {
    listen 80;
    server_name _;

    # Location block for /admin/ requests
    location /admin/ {
        proxy_pass http://localhost:8000;  # Adjust the port to match your backend server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Location block for /paintings/ requests
    location /paintings/ {
        proxy_pass http://localhost:8000;  # Adjust the port to match your backend server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Location block for /authentication/ requests
    location /authentication/ {
        proxy_pass http://localhost:8000;  # Adjust the port to match your backend server
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # comment
}