name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies # NOT NEEDED? 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy application
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          bash /home/ubuntu/deployment-scripts/deploy_backend.sh

    - name: Copy NGINX config to EC2 temp folder
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "config/nginx/backend-nginx.conf"
        target: "/home/ubuntu/temp-nginx/"

    - name: Configure NGINX
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo mv /home/ubuntu/temp-nginx/config/nginx/backend-nginx.conf /etc/nginx/sites-available/backend-nginx.conf
          sudo ln -sf /etc/nginx/sites-available/backend-nginx.conf /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl reload nginx